### ISSUE TITLE
Pulse multiple waiters

### ISSUE THREAD

**Issue by csherratt** [csherratt/pulse#1]
In order to let a pulse be waited on my multiple waiters we need a few features added.

- [ ] Cloning of pulse
- [x] Reference counting of the pulse
- [ ] Chaining of Waiting objects

One possible way:

Reference Counting
================
I think the state `AtomicUsize` could me multi tasked. We can use it as a flag and a reference count. The highest nibble would be saved for the flags. When the trigger is dropped it sets the highest bit as triggered `0x8xxx_xxxx` and for dropped `0x4xxx_xxxx`. The reference count is the lowest 30 bits.

When a Pulse is dropped it just decrements the entire. It deletes the Pulse's memory if the lowest 30 bits were equal to 1 && the dropped flag `0x4xxx_xxxx` is set. If the trigger sets the flags and finds the lowest bits were 0, it will drop the packet since there is no Pulse left.

Wait list
=======
Each wait object just needs a `next: Option<Next>` to chain wait lits. `Atom` already has a LIFO function to help locklessly chain these items.

**Comment by kvark** [comment]
Leveraging existing atomic sounds great!
